name: xeus-python-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  - python=3.13
  - xeus-python
  - numpy
  - qutip
  - matplotlib
  - ipycanvas
  - ipywidgets
  - matplotlib
  - plotly
  - pandas
  - nbformat
  - anywidget
  - scipy
  - sympy
